# Generated by Django 4.2.30 on 2026-07-15 10:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionGeometrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=40, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='StatistiqueRegionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=40)),
                ('annee', models.PositiveSmallIntegerField()),
                ('population', models.PositiveBigIntegerField()),
                ('taux_urbanisation_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taux_alphabetisation_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taux_chomage_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taux_pauvrete_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acces_internet_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('centres_sante', models.PositiveIntegerField()),
                ('taux_scolarisation_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('production_cerealiere_tonnes', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='statistiqueregionale',
            constraint=models.UniqueConstraint(fields=('region', 'annee'), name='unique_region_annee'),
        ),
    ]
